### ISSUE TITLE
Discussion: Not grouping shorthand properties at the top

### ISSUE THREAD

**Issue by AlphaGit** [MakingSense/code-style-guides#7]
Hi!

We currently have this guideline in the [JS ES6](https://github.com/MakingSense/code-style-guides/blob/master/Javascript(ES6)/README.md#objects--grouped-shorthand) docs:

---

  - [3.5](#objects--grouped-shorthand) Group your shorthand properties at the beginning of your object declaration.

    > Why? It's easier to tell which properties are using the shorthand.

    ```javascript
    const anakinSkywalker = 'Anakin Skywalker';
    const lukeSkywalker = 'Luke Skywalker';

    // bad
    const obj = {
      episodeOne: 1,
      twoJediWalkIntoACantina: 2,
      lukeSkywalker,
      episodeThree: 3,
      mayTheFourth: 4,
      anakinSkywalker,
    };

    // good
    const obj = {
      lukeSkywalker,
      anakinSkywalker,
      episodeOne: 1,
      twoJediWalkIntoACantina: 2,
      episodeThree: 3,
      mayTheFourth: 4,
    };
    ```

---

I think we should not make such recommendation, here's why:

All things being equal, any order will be the same. I don't think having shorthand properties at the top brings any particular value: you still need to read that particular line to understand that it is a shorthand property, regardless of it being in the beginning or the end of the object.

However, in the real world usage, there are certain affinities between methods / properties that have more cohesion than others, and we should allow developers to add them in an order that makes more sense for a mental model of the object.

For example:

```javascript
const invoice = {
  user: getUser(userId),
  billingAddress,
  shippingAddress,
  shippingMethod: getUserChoice(Constants.SHIPPING_METHOD)

  items: itemsForInvoice,

  subtotal: subtotalForInvoice,
  taxer: taxCalculatorFunction,
  total: currentTotal
};
```

Note how certain properties belong together for the metal model that we have of an invoice. The blank spaces help construct that mental model. Properties being put before before shorthand / alphabetical order / being a function or object is actually a criteria that does not help code readability, but gives an arbitrary decision to follow.

So, my proposal is: let's just remove this guideline.

What do you think?

**Comment by matiasbeckerle** [comment]
Agreed. In fact I use blank lines for doing this exact same thing in other places. Developers should use blank lines and arrange code carefully.

I think you can commit the deletion in order to have a diff to review. I know you created it as a debate but these are quick changes I believe, right?

**Comment by AlphaGit** [comment]
@matiasbeckerle Yup. I will also create a PR. Until I get some approvals, that will give some time for some other voices to weigh in.

Unfortunately, we don't have a standard for thes matters so I'm not sure how long I should wait until I can consider something "approved", but the more chances I can give, the better.
