### ISSUE TITLE
Discussion: not using setters and getters

### ISSUE THREAD

**Issue by AlphaGit** [MakingSense/code-style-guides#9]
In the JS ES6 code style guidelines, we have the following recommendation:

----

  - [23.2](#accessors--no-getters-setters) Do not use JavaScript getters/setters as they cause unexpected side effects and are harder to test, maintain, and reason about. Instead, if you do make accessor functions, use getVal() and setVal('hello').

    ```javascript
    // bad
    class Dragon {
      get age() {
        // ...
      }

      set age(value) {
        // ...
      }
    }

    // good
    class Dragon {
      getAge() {
        // ...
      }

      setAge(value) {
        // ...
      }
    }
    ```

----

However, I don't really see the problem. The hiccups I see with using ES6 getters and setters are:

- **They may not directly get or set a value (but may have side effects).** This is actually good: it's the OOP design that you get in almost all typed languages for exposed properties. This allows for the internal consistency of a class where the only input and output to it are the public getters, setters and methods.
- **There is a need for an internal backing variable** This is because `this.age` will actually invoke the getter function and `this.age = 15` will actually invoke the setter function. So in order to preserve a value there's a need for an internal (private! 😀) variable. This is also similar in typed languages.
- **They are not harder to test** They are just the external API to your class.
- **They are not harder to think about** A good name works miracles.

Outside of that, there are benefits to this approach (aside from the OOP class design I mentioned earlier): (taken from [this SO question](http://stackoverflow.com/q/1568091/147507))

1. When you realize you need to do more than just set and get the value, you don't have to change every file in the codebase.
2. You can perform validation here.
3. You can change the value being set.
4. You can hide the internal representation. getAddress() could actually be getting several fields for you.
5. You've insulated your public interface from changes under the sheets.
6. Some libraries expect this. Reflection, serialization, mock objects.
7. Inheriting this class, you can override default functionality.
8. You can have different access levels for getter and setter.
9. Lazy loading.
10. People can easily tell you didn't use Python.

----

**Proposal**: remove that guideline. Allow developers to use getters and setters as much as they want.

**Comment by matiasbeckerle** [comment]
Greenlight from me on this one. I don't get the point number 10... I guess it is because I don't know Python 😄
